# Generated by Django 3.1.1 on 2020-09-24 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pill',
            name='dose_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='pill',
            name='dose_date_switch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pill',
            name='doses_taken',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
