# Generated by Django 3.1.1 on 2020-09-25 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dosing',
            options={'ordering': ['-time']},
        ),
    ]
