# Generated by Django 3.1.1 on 2020-09-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200923_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pill',
            name='date_prescribed',
            field=models.DateTimeField(),
        ),
    ]
