# Generated by Django 3.1.1 on 2020-09-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200924_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosing',
            name='total_dose',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
