# Generated by Django 3.1.1 on 2020-09-21 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_emergencycontact_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencycontact',
            name='patient',
        ),
    ]
