# Generated by Django 3.1.1 on 2020-09-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_dosing_total_dose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pill',
            name='doses_taken',
            field=models.IntegerField(default=3),
        ),
    ]
