# Generated by Django 3.1.1 on 2020-09-21 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_emergencycontact_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.patient'),
        ),
    ]
