# Generated by Django 3.1.1 on 2020-09-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200924_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosing',
            name='total_dose',
        ),
        migrations.AddField(
            model_name='pill',
            name='doing_total',
            field=models.IntegerField(default=3),
        ),
    ]
