# Generated by Django 3.1.1 on 2020-09-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200924_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pill',
            name='doing_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pill',
            name='doses_taken',
            field=models.IntegerField(default=0),
        ),
    ]
