# Generated by Django 3.1.1 on 2020-09-24 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200924_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pill',
            old_name='doing_total',
            new_name='dosing_total',
        ),
    ]
