# Generated by Django 3.1.1 on 2020-09-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200924_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pill',
            name='doses_left',
        ),
        migrations.AddField(
            model_name='pill',
            name='doses_taken',
            field=models.IntegerField(default=1),
        ),
    ]
